// <auto-generated />
namespace _24HourAssignment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedChangestoLike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedChangestoLike));
        
        string IMigrationMetadata.Id
        {
            get { return "202107201749015_Added Changes to Like"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
